name: QEKF
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python
  - numpy
  - scipy
  - basemap
  - numpy-quaternion
  - matplotlib
  - pandas
  - numba
  - pip:
      - pyqt5
      - xlrd
      - openpyxl
#variables:
#  VAR1: valueA
#  VAR2: valueB
